id: IE072E4C7
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T09:54:03.627787'
last_modified: '2022-06-19T09:54:03.627800'
parser: null
source_metadata:
  title: Hagiography of Bod mkhar ba Mai tri don grub rgyal mtshan (1527–1587); Lamdre
    Lobshe, vol. nga, title no. 1
  author: མི་ཕན་ཆོས་རྒྱ་མཚོ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-09-03);
    unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), ཀུན་དགའ་རྡོ་རྗེ། (Kathmandu) (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/567
  bases:
    359b:
      title: Hagiography of Bod mkhar ba Mai tri don grub rgyal mtshan (1527–1587);
        Lamdre Lobshe, vol. nga, title no. 1
      order: 1
      base_file: 359b.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
